apiVersion: v1
kind: Secret
metadata:
  name: ubc-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: ubc
  server: "https://proxy.upbound.io/controlPlanes/2b059cbf-1554-4e12-8595-f5bc651ecef2"
  config: |
    {
      "bearerToken": "<put token here for upbound cluster",
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
