apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: upbound-ada-test-bucket 
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: upbound-ada-test-bucket
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-west-2
    acl: private
  providerConfigRef:
    name: default
