apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: demo-test-bucket-vanderkooi 
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: demo-test-bucket-vanderkooi
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: eu-west-1
    acl: private
  providerConfigRef:
    name: default
